version: '3.8'

volumes:
  pgdata:

services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=qwerty007
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testapp
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  web:
    container_name: test-project
    build: ../project/
    restart: always
    env_file:
      - ../project/envs/.env
    ports:
      - 8000:8000
    depends_on:
      - postgres